config/routes.rb
Rails.application.routes.draw do
  constraints Clearance::Constraints::SignedIn.new { |user| user.admin? } do
    root to: redirect('/dashboard'), as: :admin_root
  end

  root to: redirect('/restroom-rentals')
  get '/restroom-rentals', to: 'visitors#index', as: :landing_page
  get '/restroom-rentals/:slug', to: 'visitors#index'
  get '/sitemap.:format.:compression', to: 'sitemaps#show'

  resource :dashboard, only: [:show]

  resource :visitor_page_content, only: [:edit, :create]

  resources :inquiries, only: [:create]

  resources :reservations, shallow: true do
    resources :rentals, only: [:new]
    resources :services, only: [:new]
    resources :invoices, only: [:new]
    resource :contract, only: [:show]
  end

  resources :customers, shallow: true do
    resources :reservations, only: [:new]
  end

  resources :services, only: [:create, :edit, :update, :destroy], shallow: true do
    resource :line_item, only: [:new]
  end

  resources :rentals, only: [:create, :edit, :update, :destroy], shallow: true do
    resource :line_item, only: [:new]
  end

  resources :line_items, only: [:create, :edit, :update]

  resources :invoices

  namespace :admin do
    resources :items
    resources :service_types
    resources :seo_locations
    resources :locations
    resources :contract_terms do
      collection do
        patch :sort
      end
    end
    resources :frequently_asked_questions do
      collection do
        patch :sort
      end
    end
    resources :trailer_interior_features do
      collection do
        patch :sort
      end
    end
    resources :trailer_optional_features do
      collection do
        patch :sort
      end
    end
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    root to: "reservations#index"
  end

  ##
  # Clearance (Authentication) Routes
  #
  resources :passwords, controller: 'clearance/passwords', only: [:create, :new]
  resource :session, controller: 'clearance/sessions', only: [:create]
  resources :users, controller: 'clearance/users', only: [:create] do
    resource :password,
             controller: 'clearance/passwords',
             only: [:create, :edit, :update]
  end
  get '/sign_in' => 'clearance/sessions#new', as: 'sign_in'
  delete '/sign_out' => 'clearance/sessions#destroy', as: 'sign_out'
  get '/sign_up' => 'clearance/users#new', as: 'sign_up'
end

app/models/trailer_interior_feature.rb
class TrailerInteriorFeature < ApplicationRecord
  validates :feature, presence: true
  default_scope { order :position }
end

app/controllers/admin/trailer_interior_features_controller.rb
module Admin
  class TrailerInteriorFeaturesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = TrailerInteriorFeature.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   TrailerInteriorFeature.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
    def index
      super
      @resources = TrailerInteriorFeature.all
    end

    def sort
      params[:trailer_interior_feature].each_with_index do |id, index|
        TrailerInteriorFeature.where(id: id).update_all(position: index + 1)
      end
      head :ok
    end
  end
end

app/views/admin/trailer_interior_features/_collection.html.erb
<%#
# Collection

This partial is used on the `index` and `show` pages
to display a collection of services in an HTML table.

## Local variables:

- `collection_presenter`:
  An instance of [Administrate::Page::Collection][1].
  The table presenter uses `ResourceDashboard::COLLECTION_ATTRIBUTES` to determine
  the columns displayed in the table
- `services`:
  An ActiveModel::Relation collection of services to be displayed in the table.
  By default, the number of services is limited by pagination
  or by a hard limit to prevent excessive page load times

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Collection
%>

<table aria-labelledby="<%= table_title %>" class="table table-responsive-md">
  <thead>
  <tr class="blue-grey lighten-5">
    <th></th>
    <% collection_presenter.attribute_types.each do |attr_name, attr_type| %>
      <th class="cell-label cell-label--<%= attr_type.html_class %> cell-label--<%= collection_presenter.ordered_html_class(attr_name) %>"
          scope="col"
          role="columnheader"
          aria-sort="<%= sort_order(collection_presenter.ordered_html_class(attr_name)) %>">
        <%= t(
                "helpers.label.#{collection_presenter.resource_name}.#{attr_name}",
                default: attr_name.to_s,
                ).titleize %>
      </th>
    <% end %>
    <th></th>
  </tr>
  </thead>

  <tbody class="drag-drop-sortable" data-url="<%= sort_admin_trailer_interior_features_path %>">
  <% resources.each do |resource| %>
    <tr class="js-table-row"
        id="<%= dom_id(resource)%>"
        tabindex="0"
        <% if valid_action? :show, collection_presenter.resource_name %>
        <%= %(role=link data-url=#{polymorphic_path([namespace, resource])}) %>
        <% end %>
        >
      <td class="text-center px-0 sort-handle"><%= fa_icon('sort') %></td>
      <% collection_presenter.attributes_for(resource).each do |attribute| %>
        <td class="cell-data cell-data--<%= attribute.html_class %>">
          <% if show_action? :show, resource -%>
            <a href="<%= polymorphic_path([namespace, resource]) -%>"
               class="action-show"
            >
              <%= render_field attribute %>
            </a>
          <% end -%>
        </td>
      <% end %>

      <td class="buttons-column d-flex justify-content-around">
        <% if valid_action? :edit, collection_presenter.resource_name %>
          <%= link_to(
                  fa_icon('pencil-alt', text: 'Edit'),
                  [:edit, namespace, resource],
                  class: "text-info",
                  ) if show_action? :edit, resource%>
        <% end %>

        <% if valid_action? :destroy, collection_presenter.resource_name %>
          <%= link_to(
                  fa_icon('trash', text: 'Delete'),
                  [namespace, resource],
                  class: "text-danger",
                  method: :delete,
                  data: { confirm: t("administrate.actions.confirm") }
              ) if show_action? :destroy, resource %>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/admin/trailer_interior_features/index.html.erb
<div class="container-fluid">
  <header class="d-flex justify-content-between py-2">
    <h1 class="d-inline-block">Manage Content</h1>
    <%= back_button %>
  </header>
  <div class="card">
    <div class="card-header">
      <ul class="nav nav-tabs card-header-tabs">
        <li class="nav-item">
          <%= link_to "General Content", edit_visitor_page_content_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Frequently asked questions", admin_frequently_asked_questions_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Trailer interior features", admin_trailer_interior_features_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Trailer optional features", admin_trailer_optional_features_path, class: 'nav-link' %>
        </li>
      </ul>
    </div>
    <div class="card-body px-0">
      <% content_for(:title) do %>
        <%= display_resource_name(page.resource_name) %>
      <% end %>


      <header class="main-content__header d-flex justify-content-between py-2 px-3" role="banner">
        <h1 class="main-content__page-title d-inline-block" id="page-title">
          <%= content_for(:title) %>
        </h1>

        <% if show_search_bar %>
          <%= render(
                  "search",
                  search_term: search_term,
                  resource_name: display_resource_name(page.resource_name)
              ) %>
        <% end %>

        <%= link_to(fa_icon('plus', text: t(
            "administrate.actions.new_resource",
            name: page.resource_name.titleize.downcase
        )),
                    [:new, namespace, page.resource_path],
                    class: "btn btn-primary",
                    data: { role: "new-#{page.resource_name}" },
                    ) if valid_action?(:new) && show_action?(:new, new_resource) %>
      </header>

      <section class="main-content__body main-content__body--flush">
        <%= render(
                "collection",
                collection_presenter: page,
                resources: resources,
                table_title: "page-title"
            ) %>

        <%= paginate resources, theme: 'twitter-bootstrap-4' %>
      </section>
    </div>
  </div>
</div>
</div>